
import type { Metadata } from 'next'
import 'bulma/css/bulma.css' 

export const metadata: Metadata = {
  title: 'Vendas APP',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body >{children}</body>
    </html>
  )
}
